# Generated by Django 3.2.25 on 2025-09-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_questions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
