# Generated by Django 3.2.25 on 2025-09-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_user_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_profile',
            field=models.ImageField(blank=True, default='static/images/user.jpg', null=True, upload_to='account/profile'),
        ),
    ]
