# Generated by Django 3.2.25 on 2025-09-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_user_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to='account/profile'),
        ),
    ]
