# Generated by Django 3.2.25 on 2025-09-15 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20250911_1942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='MoviePoster',
        ),
    ]
