# Generated by Django 3.2.25 on 2025-09-15 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_rename_movie_movieposter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rating', models.FloatField(default=0.0)),
                ('duration_minutes', models.PositiveIntegerField(help_text='مدت فیلم به دقیقه')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movies/posters/')),
                ('trailer', models.FileField(blank=True, null=True, upload_to='movies/trailers/')),
                ('type', models.CharField(choices=[('poster', 'poster'), ('product', 'product')], default='product', max_length=10)),
                ('actors', models.ManyToManyField(related_name='movies', to='movie.Actor')),
                ('genres', models.ManyToManyField(related_name='movies', to='movie.Genre')),
            ],
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movie.movie'),
        ),
        migrations.DeleteModel(
            name='MoviePoster',
        ),
    ]
