# Generated by Django 3.2.25 on 2025-09-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20250915_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('poster', 'poster'), ('product', 'product'), ('future', 'future')], default='product', max_length=10),
        ),
    ]
