# Generated by Django 3.2.25 on 2025-09-16 08:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0005_alter_movie_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rating', models.FloatField(default=0.0)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='series/posters/')),
                ('trailer', models.FileField(blank=True, null=True, upload_to='series/trailers/')),
                ('type', models.CharField(choices=[('poster', 'poster'), ('product', 'product'), ('future', 'future')], default='product', max_length=10)),
                ('actors', models.ManyToManyField(related_name='series', to='movie.Actor')),
                ('genres', models.ManyToManyField(related_name='series', to='movie.Genre')),
            ],
        ),
        migrations.RenameModel(
            old_name='Rating',
            new_name='MovieRating',
        ),
        migrations.CreateModel(
            name='SeriesRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movie.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'series')},
            },
        ),
    ]
