# Generated by Django 3.2.25 on 2025-09-16 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20250916_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(help_text='مدت قسمت به دقیقه')),
                ('episode_number', models.PositiveIntegerField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='series/episodes/')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movie.series')),
            ],
            options={
                'ordering': ['episode_number'],
            },
        ),
    ]
