# Generated by Django 3.2.25 on 2025-09-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='series/episodes/poster/'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='series/episodes/video/'),
        ),
    ]
