# Generated by Django 3.2.25 on 2025-09-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20250916_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
