# Generated by Django 3.2.25 on 2025-09-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_alter_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
