# Generated by Django 3.2.25 on 2025-09-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_series_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
